#!/usr/bin/bash

if [ "$EUID" -ne 0 ]; then
  echo -e "Precisa rodar como root! (sudo ${0##*/})"
  exit 1
fi

desinstalar_(){
  #cd ~
  sudo find / -type d -iname ceifador -exec rm -rf {} \; 2>/dev/null
  #sudo find / -type f -iname ceifador -exec rm -rf {} \; 2>/dev/null
  echo -e "Ceifador desinstalado!\nAté a próxima! <3"
  #cd -
  exit 0
}

if [[ -z "$1" ]]; then
  echo -e " [1] Desinstalar o ceifador."
  echo -e " [0] Sair do menu."
  read -rp " Selecione a opção: " OPCAO_
  case "$OPCAO_" in
    1) desinstalar_ ;;
    0) exit 0 ;;
    *) echo -e "Opção inválida!" ;
      exit 1 ;;
  esac
fi
